baseURL = 'https://sooniln.github.io/'
locale = 'en-us'
title = 'Soonil Nagarkar'
theme = 'FixIt'

[pagination]
  pagerSize = 10

[outputs]
  home = ["html", "rss", "archives", "search"]

[params]
  [params.author]
    name = "Soonil Nagarkar"

  [params.app]
    svgFavicon = "/favicon.svg"

  [params.home.profile]
    enable = true
    title = "Soonil Nagarkar"

  [params.search]
    enable = true
    type = "fuse"

  [params.social]
    GitHub = "sooniln"
    Linkedin = "sooniln"

  [params.page]
    license = ""
    linkToVscode = false

  [params.page.toc]
    position = "left"
    auto = false

  [params.page.math]
    enable = true
    type = "katex"

  [params.page.share]
    enable = false

  [params.cookieconsent]
    enable = false

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$']]
    inline = [['$', '$']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
