baseURL = 'https://sooniln.github.io/'
locale = 'en-us'
title = 'Soonil Nagarkar'
theme = 'FixIt'

[pagination]
  pagerSize = 10

[outputs]
  home = ["html", "rss", "archives"]

[menus]
  [[menus.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 1
    [menus.main.params]
      icon = "fa-solid fa-archive"

[params]
  [params.author]
    name = "Soonil Nagarkar"

  [params.app]
    svgFavicon = "/favicon.svg"

  [params.home.profile]
    enable = true
    title = "Soonil Nagarkar"

  [params.social]
    GitHub = "sooniln"
    Linkedin = "sooniln"

  [params.page]
    license = ""
    linkToVscode = false
    wordCount = false
    readingTime = false

  [params.page.toc]
    position = "left"
    auto = false

  [params.page.math]
    enable = true
    type = "katex"

  [params.page.share]
    enable = false

  [params.cookieconsent]
    enable = false

  [params.codeblock]
    lineNosToggler = false
    lineWrapToggler = false
    copyable = false
    max_shown_lines = 50

[markup.highlight]
  # ~~~~~~~~~~ necessary configurations ~~~~~~~~~~
  # https://github.com/hugo-fixit/FixIt/issues/43
  codeFences = true
  noClasses = false
  # ~~~~~~~~~~ necessary configurations ~~~~~~~~~~

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$']]
    inline = [['$', '$']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
