baseURL = 'https://sooniln.github.io/'
locale = 'en-us'
title = 'Soonil Nagarkar'
theme = 'PaperMod'
paginate = 10

[params]
  author = "Soonil Nagarkar"

[params.assets]
  favicon = "favicon.svg"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/sooniln/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/sooniln"

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$']]
    inline = [['$', '$']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
